# Generated by Django 3.2.7 on 2021-09-19 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_dev_remote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('role', models.CharField(choices=[('1st', 'First Round'), ('2nd', 'Second Round'), ('3rd', 'Final Round')], default='1st', max_length=3)),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dev')),
            ],
        ),
    ]
