# Generated by Django 3.2.7 on 2021-09-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateField(verbose_name='Interview Date:'),
        ),
    ]
